arm: make asm code more generic + other fixes
This fixes compilation for Raspberry Pi Zero W target where movw and
movt are not supported.

Assembler messages:
Error: selected processor does not support `movw r0,#0x2f00' in ARM mode
Error: selected processor does not support `movt r0,#0x8005' in ARM mode

Add -ffreestanding so that gcc doesn't insert a call to memcpy/memset in
parasite code.